# CircleCI Configuration for International Payments Portal
version: 2.1

orbs:
  node: circleci/node@5.0.0
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  main:
    jobs:
      - build-and-test
      - sonarcloud/scan:
          requires:
            - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17
      - image: cimg/mongo:6.0
    steps:
      - checkout
      
      # Install backend dependencies
      - run:
          name: Install Backend Dependencies
          command: |
            cd InternationalPaymentBackend
            npm install
      
      # Install frontend dependencies  
      - run:
          name: Install Frontend Dependencies
          command: |
            cd international-payments-app
            npm install
      
      # Lint backend code
      - run:
          name: Lint Backend Code
          command: |
            cd InternationalPaymentBackend
            npx eslint . --ext .js || echo "ESLint not configured, skipping..."
      
      # Lint frontend code
      - run:
          name: Lint Frontend Code  
          command: |
            cd international-payments-app
            npm run lint || echo "Lint script not found, skipping..."
      
      # Run backend tests (if any)
      - run:
          name: Run Backend Tests
          command: |
            cd InternationalPaymentBackend
            npm test || echo "No tests configured for backend"
      
      # Run frontend tests
      - run:
          name: Run Frontend Tests
          command: |
            cd international-payments-app
            CI=true npm test -- --coverage --watchAll=false --testResultsProcessor=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ~/test-results/jest
            JEST_JUNIT_OUTPUT_NAME: results.xml
      
      # Build frontend
      - run:
          name: Build Frontend
          command: |
            cd international-payments-app
            npm run build
      
      # Security audit
      - run:
          name: Security Audit - Backend
          command: |
            cd InternationalPaymentBackend
            npm audit --audit-level moderate || echo "Security issues found but continuing..."
      
      - run:
          name: Security Audit - Frontend
          command: |
            cd international-payments-app
            npm audit --audit-level moderate || echo "Security issues found but continuing..."
      
      # Store test results
      - store_test_results:
          path: ~/test-results
      
      # Store coverage reports
      - store_artifacts:
          path: international-payments-app/coverage
      
      # Store build artifacts
      - store_artifacts:
          path: international-payments-app/build